services:
  db: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=YourPassword123
      - ACCEPT_EULA=Y
    ports:
     - "1433:1433"
  apitodolist:    
    build:
      context: .
      dockerfile: ApiTodoList/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ApiTodoList;User=sa;Password=YourPassword123;MultipleActiveResultSets=true;Trust Server Certificate=True;
    depends_on:
      - db
    ports:
      - "5000:8080"
      - "5001:8081"
